---
- name: Deploy Weather Dashboard
  hosts: localhost
  connection: local
  tasks:
    - name: Run Terraform Init
      command: terraform init
      args:
        chdir: ./terraform

    - name: Apply Terraform configuration
      command: terraform apply -auto-approve
      args:
        chdir: ./terraform

    - name: Verify running containers
      command: docker ps
