version: "3.8"

services:
  backend:
    build: ./backend
    container_name: weather-backend
    env_file: ./backend/.env
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: weather-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
