version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    container_name: weather-backend

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    container_name: weather-frontend
    depends_on:
      - backend
